# Generated by Django 4.2.16 on 2026-06-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolucionFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefijo', models.CharField(blank=True, max_length=10, null=True)),
                ('numero_resolucion', models.CharField(max_length=50, unique=True)),
                ('rango_inicial', models.IntegerField()),
                ('rango_final', models.IntegerField()),
                ('consecutivo_actual', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Resolución de Facturación',
                'verbose_name_plural': 'Resoluciones de Facturación',
                'db_table': 'facturacion_resolucion',
            },
        ),
    ]
