# Generated by Django 4.2.16 on 2026-06-28 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_condicionpago_impuesto_metodopago_and_more'),
        ('facturacion', '0002_resolucionfacturacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResolucionFacturacion',
        ),
        migrations.AddField(
            model_name='factura',
            name='condicion_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configuracion.condicionpago'),
        ),
        migrations.AlterField(
            model_name='facturaimpuesto',
            name='impuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.impuesto'),
        ),
        migrations.AlterField(
            model_name='pagofactura',
            name='metodo_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.metodopago'),
        ),
        migrations.DeleteModel(
            name='Impuesto',
        ),
    ]
