# Generated by Django 5.0.14 on 2026-03-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CLIENTE', 'Cliente'), ('PRODUCTO', 'Producto'), ('VENTA', 'Venta'), ('COMPRA', 'Compra'), ('CAJA', 'Caja')], max_length=20)),
                ('accion', models.CharField(choices=[('CREADO', 'Creado'), ('ACTUALIZADO', 'Actualizado'), ('ELIMINADO', 'Eliminado')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='COMPLETADO', max_length=20)),
            ],
            options={
                'verbose_name': 'Actividad del Sistema',
                'verbose_name_plural': 'Actividades del Sistema',
                'db_table': 'dashboard_actividad',
                'ordering': ['-fecha'],
            },
        ),
    ]
