# Generated by Django 6.0.1 on 2026-02-24 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividadsistema',
            options={'ordering': ['-fecha'], 'verbose_name': 'Actividad del Sistema', 'verbose_name_plural': 'Actividades del Sistema'},
        ),
        migrations.AlterModelTable(
            name='actividadsistema',
            table='dashboard_actividad',
        ),
    ]
