# Generated by Django 5.0.14 on 2026-03-19 00:48

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArqueoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PARCIAL', 'Arqueo parcial'), ('CIERRE', 'Arqueo de cierre')], default='PARCIAL', max_length=10)),
                ('monto_contado', models.DecimalField(decimal_places=2, help_text='Total del dinero contado físicamente', max_digits=12)),
                ('monto_esperado', models.DecimalField(decimal_places=2, help_text='Saldo que el sistema esperaba (snapshot al momento del arqueo)', max_digits=12)),
                ('detalle_billetes', models.JSONField(blank=True, default=dict, help_text='Detalle del conteo por denominación de billetes')),
                ('diferencia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Diferencia = monto_contado - monto_esperado', max_digits=12)),
                ('observaciones', models.TextField(blank=True, help_text='Notas o justificación de la diferencia', null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Arqueo de Caja',
                'verbose_name_plural': 'Arqueos de Caja',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la caja (ej: Caja Principal)', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción o ubicación de la caja', null=True)),
                ('activa', models.BooleanField(default=True, help_text='Si la caja está habilitada para operar')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del método de pago (ej: Efectivo, Tarjeta)', max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, aparece como opción al registrar movimientos')),
                ('es_efectivo', models.BooleanField(default=False, help_text='Marcar si este método cuenta como dinero en efectivo físico')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('APERTURA', 'Apertura de caja'), ('INGRESO_VENTA', 'Ingreso por venta'), ('INGRESO_MANUAL', 'Ingreso manual'), ('EGRESO_COMPRA', 'Egreso por compra'), ('EGRESO_GASTO', 'Egreso por gasto'), ('EGRESO_RETIRO', 'Retiro de dinero')], db_index=True, help_text='Tipo de movimiento', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Valor del movimiento (siempre positivo)', max_digits=12)),
                ('descripcion', models.TextField(help_text='Descripción del movimiento')),
                ('fecha', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='SesionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Dinero con el que se abrió la caja', max_digits=12)),
                ('monto_final', models.DecimalField(blank=True, decimal_places=2, help_text='Saldo calculado al cerrar (sistema)', max_digits=12, null=True)),
                ('monto_contado', models.DecimalField(blank=True, decimal_places=2, help_text='Dinero contado físicamente al cerrar', max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], db_index=True, default='ABIERTA', max_length=10)),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de apertura')),
                ('fecha_cierre', models.DateTimeField(blank=True, help_text='Fecha y hora de cierre', null=True)),
                ('observaciones_apertura', models.TextField(blank=True, help_text='Notas al abrir la caja', null=True)),
                ('observaciones_cierre', models.TextField(blank=True, help_text='Notas al cerrar la caja', null=True)),
            ],
            options={
                'verbose_name': 'Sesión de Caja',
                'verbose_name_plural': 'Sesiones de Caja',
                'ordering': ['-fecha_apertura'],
            },
        ),
    ]
