# Generated by Django 6.0.1 on 2026-03-09 00:19

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
        ('compras', '0002_initial'),
        ('ventas', '0004_venta_impuesto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArqueoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PARCIAL', 'Arqueo parcial'), ('CIERRE', 'Arqueo de cierre')], default='PARCIAL', max_length=10)),
                ('monto_contado', models.DecimalField(decimal_places=2, help_text='Total del dinero contado físicamente', max_digits=12)),
                ('monto_esperado', models.DecimalField(decimal_places=2, help_text='Saldo que el sistema esperaba (snapshot al momento del arqueo)', max_digits=12)),
                ('detalle_billetes', models.JSONField(blank=True, default=dict, help_text='Detalle del conteo por denominación de billetes')),
                ('diferencia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Diferencia = monto_contado - monto_esperado', max_digits=12)),
                ('observaciones', models.TextField(blank=True, help_text='Notas o justificación de la diferencia', null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(help_text='Usuario que realizó el arqueo', on_delete=django.db.models.deletion.PROTECT, related_name='arqueos_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arqueo de Caja',
                'verbose_name_plural': 'Arqueos de Caja',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la caja (ej: Caja Principal)', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción o ubicación de la caja', null=True)),
                ('activa', models.BooleanField(default=True, help_text='Si la caja está habilitada para operar')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SesionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Dinero con el que se abrió la caja', max_digits=12)),
                ('monto_final', models.DecimalField(blank=True, decimal_places=2, help_text='Saldo calculado al cerrar (sistema)', max_digits=12, null=True)),
                ('monto_contado', models.DecimalField(blank=True, decimal_places=2, help_text='Dinero contado físicamente al cerrar', max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], db_index=True, default='ABIERTA', max_length=10)),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de apertura')),
                ('fecha_cierre', models.DateTimeField(blank=True, help_text='Fecha y hora de cierre', null=True)),
                ('observaciones_apertura', models.TextField(blank=True, help_text='Notas al abrir la caja', null=True)),
                ('observaciones_cierre', models.TextField(blank=True, help_text='Notas al cerrar la caja', null=True)),
                ('caja', models.ForeignKey(help_text='Caja a la que pertenece esta sesión', on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='caja.caja')),
                ('usuario', models.ForeignKey(help_text='Usuario que abrió esta caja', on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Caja',
                'verbose_name_plural': 'Sesiones de Caja',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.DeleteModel(
            name='CajaDiaria',
        ),
        migrations.AlterModelOptions(
            name='metodopago',
            options={'ordering': ['nombre'], 'verbose_name': 'Método de Pago', 'verbose_name_plural': 'Métodos de Pago'},
        ),
        migrations.AddField(
            model_name='metodopago',
            name='es_efectivo',
            field=models.BooleanField(default=False, help_text='Marcar si este método cuenta como dinero en efectivo físico'),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='referencia_compra',
            field=models.ForeignKey(blank=True, help_text='Compra asociada a este movimiento (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='compras.compra'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='referencia_venta',
            field=models.ForeignKey(blank=True, help_text='Venta asociada a este movimiento (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='usuario',
            field=models.ForeignKey(default=1, help_text='Usuario que registró el movimiento', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si está activo, aparece como opción al registrar movimientos'),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='nombre',
            field=models.CharField(help_text='Nombre del método de pago (ej: Efectivo, Tarjeta)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='descripcion',
            field=models.TextField(help_text='Descripción del movimiento'),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='fecha',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='metodo_pago',
            field=models.ForeignKey(help_text='Método de pago utilizado', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='caja.metodopago'),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='monto',
            field=models.DecimalField(decimal_places=2, help_text='Valor del movimiento (siempre positivo)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='tipo',
            field=models.CharField(choices=[('APERTURA', 'Apertura de caja'), ('INGRESO_VENTA', 'Ingreso por venta'), ('INGRESO_MANUAL', 'Ingreso manual'), ('EGRESO_COMPRA', 'Egreso por compra'), ('EGRESO_GASTO', 'Egreso por gasto'), ('EGRESO_RETIRO', 'Retiro de dinero')], db_index=True, help_text='Tipo de movimiento', max_length=20),
        ),
        migrations.AddField(
            model_name='arqueocaja',
            name='sesion',
            field=models.ForeignKey(help_text='Sesión de caja a la que pertenece este arqueo', on_delete=django.db.models.deletion.PROTECT, related_name='arqueos', to='caja.sesioncaja'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='sesion',
            field=models.ForeignKey(default=1, help_text='Sesión de caja a la que pertenece este movimiento', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='caja.sesioncaja'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['sesion', 'tipo'], name='caja_movimi_sesion__9ec20a_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['tipo', 'fecha'], name='caja_movimi_tipo_db233a_idx'),
        ),
        migrations.AddIndex(
            model_name='sesioncaja',
            index=models.Index(fields=['estado', 'usuario'], name='caja_sesion_estado_c6ddfb_idx'),
        ),
        migrations.AddIndex(
            model_name='sesioncaja',
            index=models.Index(fields=['estado', 'caja'], name='caja_sesion_estado_a14971_idx'),
        ),
        migrations.AddIndex(
            model_name='sesioncaja',
            index=models.Index(fields=['fecha_apertura'], name='caja_sesion_fecha_a_d402c3_idx'),
        ),
    ]
