# Generated by Django 5.0.14 on 2026-03-14 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caja', '0001_initial'),
        ('compras', '0001_initial'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='referencia_compra',
            field=models.ForeignKey(blank=True, help_text='Compra asociada a este movimiento (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='compras.compra'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='referencia_venta',
            field=models.ForeignKey(blank=True, help_text='Venta asociada a este movimiento (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario que registró el movimiento', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='caja',
            field=models.ForeignKey(help_text='Caja a la que pertenece esta sesión', on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='caja.caja'),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario que abrió esta caja', on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_caja', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='sesion',
            field=models.ForeignKey(help_text='Sesión de caja a la que pertenece este movimiento', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='caja.sesioncaja'),
        ),
        migrations.AddField(
            model_name='arqueocaja',
            name='sesion',
            field=models.ForeignKey(help_text='Sesión de caja a la que pertenece este arqueo', on_delete=django.db.models.deletion.PROTECT, related_name='arqueos', to='caja.sesioncaja'),
        ),
        migrations.AddIndex(
            model_name='sesioncaja',
            index=models.Index(fields=['estado', 'usuario'], name='caja_sesion_estado_c6ddfb_idx'),
        ),
        migrations.AddIndex(
            model_name='sesioncaja',
            index=models.Index(fields=['estado', 'caja'], name='caja_sesion_estado_a14971_idx'),
        ),
        migrations.AddIndex(
            model_name='sesioncaja',
            index=models.Index(fields=['fecha_apertura'], name='caja_sesion_fecha_a_d402c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='sesioncaja',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ABIERTA')), fields=('caja',), name='unique_sesion_abierta_por_caja'),
        ),
        migrations.AddConstraint(
            model_name='sesioncaja',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ABIERTA')), fields=('usuario',), name='unique_sesion_abierta_por_usuario'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['sesion', 'tipo'], name='caja_movimi_sesion__9ec20a_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['tipo', 'fecha'], name='caja_movimi_tipo_db233a_idx'),
        ),
    ]
