# Generated by Django 6.0.1 on 2026-03-12 21:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_arqueocaja_caja_sesioncaja_delete_cajadiaria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sesioncaja',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ABIERTA')), fields=('caja',), name='unique_sesion_abierta_por_caja'),
        ),
        migrations.AddConstraint(
            model_name='sesioncaja',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ABIERTA')), fields=('usuario',), name='unique_sesion_abierta_por_usuario'),
        ),
    ]
