# Generated by Django 4.2.16 on 2026-06-28 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_delete_resolucionfacturacion_factura_condicion_pago_and_more'),
        ('configuracion', '0002_condicionpago_impuesto_metodopago_and_more'),
        ('caja', '0003_metodopago_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='metodo_pago',
            field=models.ForeignKey(help_text='Método de pago utilizado', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='configuracion.metodopago'),
        ),
        migrations.DeleteModel(
            name='MetodoPago',
        ),
    ]
