# Generated by Django 6.0.1 on 2026-02-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='documento',
            new_name='numero_documento',
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('CEDULA', 'Cédula de ciudadanía'), ('NIT', 'NIT'), ('CEDULA_EXTRANJERA', 'Cédula extranjera')], default='CEDULA', max_length=30),
        ),
    ]
