# Generated by Django 5.0.14 on 2026-03-14 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(help_text='Nombre comercial que aparecerá en facturas y documentos', max_length=150, verbose_name='Nombre de la empresa')),
                ('razon_social', models.CharField(blank=True, default='', help_text='Razón social legal de la empresa', max_length=200, verbose_name='Razón social')),
                ('nit', models.CharField(help_text='NIT o documento tributario de la empresa', max_length=50, verbose_name='NIT / Documento de identidad')),
                ('telefono', models.CharField(max_length=30, verbose_name='Teléfono principal')),
                ('telefono_secundario', models.CharField(blank=True, default='', max_length=30, verbose_name='Teléfono secundario')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email de contacto')),
                ('sitio_web', models.URLField(blank=True, default='', verbose_name='Sitio web')),
                ('direccion', models.TextField(help_text='Dirección física de la empresa', verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, default='', max_length=100, verbose_name='Ciudad')),
                ('departamento', models.CharField(blank=True, default='', max_length=100, verbose_name='Departamento / Estado')),
                ('pais', models.CharField(default='Colombia', max_length=100, verbose_name='País')),
                ('logo', models.ImageField(blank=True, help_text='Logo que aparecerá en facturas y reportes (PNG o JPG recomendado)', null=True, upload_to='configuracion/logos/', verbose_name='Logo de la empresa')),
                ('regimen_fiscal', models.CharField(choices=[('SIMPLIFICADO', 'Régimen Simplificado'), ('COMUN', 'Régimen Común'), ('ESPECIAL', 'Régimen Especial'), ('NO_RESPONSABLE', 'No Responsable de IVA')], default='COMUN', max_length=20, verbose_name='Régimen fiscal')),
                ('impuesto_porcentaje', models.DecimalField(decimal_places=2, default=19.0, help_text='Porcentaje de IVA aplicado por defecto (ej: 19.00 para 19%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de IVA (%)')),
                ('aplicar_impuesto_por_defecto', models.BooleanField(default=True, help_text='Si está activo, el IVA se aplica automáticamente a todos los productos', verbose_name='Aplicar IVA por defecto en ventas')),
                ('moneda', models.CharField(choices=[('COP', 'Peso Colombiano (COP)'), ('USD', 'Dólar Americano (USD)'), ('EUR', 'Euro (EUR)'), ('MXN', 'Peso Mexicano (MXN)'), ('PEN', 'Sol Peruano (PEN)'), ('CLP', 'Peso Chileno (CLP)'), ('ARS', 'Peso Argentino (ARS)')], default='COP', max_length=10, verbose_name='Moneda principal')),
                ('simbolo_moneda', models.CharField(default='$', help_text='Símbolo que se muestra antes de los valores (ej: $, €, S/)', max_length=5, verbose_name='Símbolo de moneda')),
                ('decimales_precio', models.PositiveSmallIntegerField(default=2, help_text='Número de decimales para mostrar precios (0-4)', validators=[django.core.validators.MaxValueValidator(4)], verbose_name='Decimales en precios')),
                ('tasa_cambio', models.DecimalField(decimal_places=4, default=1.0, help_text='Tasa de conversión respecto a la moneda base (ej: 1 USD = 4000 COP)', max_digits=12, verbose_name='Tasa de cambio')),
                ('prefijo_factura', models.CharField(default='FAC', help_text='Prefijo para el número de factura (ej: FAC → FAC-0001)', max_length=10, verbose_name='Prefijo de factura')),
                ('consecutivo_factura', models.PositiveIntegerField(default=1, help_text='Número desde el cual se generará la próxima factura', verbose_name='Consecutivo actual de factura')),
                ('prefijo_compra', models.CharField(default='COM', help_text='Prefijo para el número de compra (ej: COM → COM-0001)', max_length=10, verbose_name='Prefijo de compra')),
                ('consecutivo_compra', models.PositiveIntegerField(default=1, verbose_name='Consecutivo actual de compra')),
                ('prefijo_recibo', models.CharField(default='REC', help_text='Prefijo para recibos de caja/POS', max_length=10, verbose_name='Prefijo de recibo POS')),
                ('consecutivo_recibo', models.PositiveIntegerField(default=1, verbose_name='Consecutivo actual de recibo')),
                ('digitos_consecutivo', models.PositiveSmallIntegerField(default=4, help_text='Cantidad de dígitos para rellenar con ceros (ej: 4 → 0001, 6 → 000001)', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(8)], verbose_name='Dígitos del consecutivo')),
                ('stock_minimo_global', models.PositiveIntegerField(default=5, help_text='Stock mínimo por defecto al crear un producto. Se puede sobreescribir producto por producto.', verbose_name='Stock mínimo global')),
                ('alertar_stock_bajo', models.BooleanField(default=True, help_text='Mostrar alertas en el dashboard cuando hay productos con stock bajo', verbose_name='Alertar cuando el stock esté bajo')),
                ('permitir_descuentos', models.BooleanField(default=True, verbose_name='Permitir descuentos en ventas')),
                ('descuento_maximo', models.DecimalField(decimal_places=2, default=30.0, help_text='Porcentaje máximo de descuento que puede aplicar un vendedor', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Descuento máximo permitido (%)')),
                ('permitir_venta_sin_stock', models.BooleanField(default=False, help_text='Si está activo, se pueden hacer ventas aunque no haya stock disponible', verbose_name='Permitir vender con stock en 0')),
                ('terminos_condiciones', models.TextField(blank=True, default='', help_text='Texto que aparecerá en la parte inferior de las facturas', verbose_name='Términos y condiciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Configuración General',
                'verbose_name_plural': 'Configuración General',
            },
        ),
    ]
