# Generated by Django 6.0.1 on 2026-01-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=150)),
                ('nit', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=30)),
                ('direccion', models.TextField()),
                ('impuesto_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('moneda', models.CharField(default='COP', max_length=10)),
            ],
            options={
                'verbose_name': 'Configuración General',
                'verbose_name_plural': 'Configuración General',
            },
        ),
    ]
