# Generated by Django 4.2.16 on 2026-06-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Contado, Crédito 30 días', max_length=50, unique=True)),
                ('dias_plazo', models.PositiveIntegerField(default=0, help_text='Días de plazo para el pago. 0 para pago de contado.')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Condición de Pago',
                'verbose_name_plural': 'Condiciones de Pago',
                'db_table': 'configuracion_condicion_pago',
                'ordering': ['dias_plazo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: IVA 19%, ReteFuente 2.5%', max_length=50, unique=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Impuesto',
                'verbose_name_plural': 'Impuestos',
                'db_table': 'configuracion_impuesto',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del método de pago (ej: Efectivo, Tarjeta)', max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, aparece como opción al registrar movimientos')),
                ('es_efectivo', models.BooleanField(default=False, help_text='Marcar si este método cuenta como dinero en efectivo físico')),
                ('tipo', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito')], default='CONTADO', help_text='CONTADO: requiere saldo en caja y genera egreso inmediato. CREDITO: no afecta caja y genera una Cuenta por Pagar.', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'db_table': 'configuracion_metodo_pago',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='cuenta_cxc_clientes',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Cuenta Contable CxC Clientes'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='cuenta_impuestos',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Cuenta Contable Impuestos'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='cuenta_ventas',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Cuenta Contable Ventas'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='fecha_fin_resolucion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha fin resolución'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='fecha_inicio_resolucion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha inicio resolución'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='numero_resolucion_factura',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de resolución DIAN'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='plantilla_correo_factura',
            field=models.TextField(blank=True, default='', verbose_name='Plantilla Correo Factura'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='plantilla_factura_pdf',
            field=models.CharField(default='estandar', max_length=50, verbose_name='Plantilla PDF Factura'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='rango_final_factura',
            field=models.PositiveIntegerField(default=10000, verbose_name='Rango final autorizado'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='rango_inicial_factura',
            field=models.PositiveIntegerField(default=1, verbose_name='Rango inicial autorizado'),
        ),
    ]
