# Generated by Django 6.0.1 on 2026-02-26 14:50

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciongeneral',
            name='alertar_stock_bajo',
            field=models.BooleanField(default=True, help_text='Mostrar alertas en el dashboard cuando hay productos con stock bajo', verbose_name='Alertar cuando el stock esté bajo'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='aplicar_impuesto_por_defecto',
            field=models.BooleanField(default=True, help_text='Si está activo, el IVA se aplica automáticamente a todos los productos', verbose_name='Aplicar IVA por defecto en ventas'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='consecutivo_compra',
            field=models.PositiveIntegerField(default=1, verbose_name='Consecutivo actual de compra'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='consecutivo_factura',
            field=models.PositiveIntegerField(default=1, help_text='Número desde el cual se generará la próxima factura', verbose_name='Consecutivo actual de factura'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='consecutivo_recibo',
            field=models.PositiveIntegerField(default=1, verbose_name='Consecutivo actual de recibo'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='decimales_precio',
            field=models.PositiveSmallIntegerField(default=2, help_text='Número de decimales para mostrar precios (0-4)', validators=[django.core.validators.MaxValueValidator(4)], verbose_name='Decimales en precios'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='departamento',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Departamento / Estado'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='descuento_maximo',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Porcentaje máximo de descuento que puede aplicar un vendedor', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Descuento máximo permitido (%)'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='digitos_consecutivo',
            field=models.PositiveSmallIntegerField(default=4, help_text='Cantidad de dígitos para rellenar con ceros (ej: 4 → 0001, 6 → 000001)', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(8)], verbose_name='Dígitos del consecutivo'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email de contacto'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo que aparecerá en facturas y reportes (PNG o JPG recomendado)', null=True, upload_to='configuracion/logos/', verbose_name='Logo de la empresa'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='pais',
            field=models.CharField(default='Colombia', max_length=100, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='permitir_descuentos',
            field=models.BooleanField(default=True, verbose_name='Permitir descuentos en ventas'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='permitir_venta_sin_stock',
            field=models.BooleanField(default=False, help_text='Si está activo, se pueden hacer ventas aunque no haya stock disponible', verbose_name='Permitir vender con stock en 0'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='prefijo_compra',
            field=models.CharField(default='COM', help_text='Prefijo para el número de compra (ej: COM → COM-0001)', max_length=10, verbose_name='Prefijo de compra'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='prefijo_factura',
            field=models.CharField(default='FAC', help_text='Prefijo para el número de factura (ej: FAC → FAC-0001)', max_length=10, verbose_name='Prefijo de factura'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='prefijo_recibo',
            field=models.CharField(default='REC', help_text='Prefijo para recibos de caja/POS', max_length=10, verbose_name='Prefijo de recibo POS'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='razon_social',
            field=models.CharField(blank=True, default='', help_text='Razón social legal de la empresa', max_length=200, verbose_name='Razón social'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='regimen_fiscal',
            field=models.CharField(choices=[('SIMPLIFICADO', 'Régimen Simplificado'), ('COMUN', 'Régimen Común'), ('ESPECIAL', 'Régimen Especial'), ('NO_RESPONSABLE', 'No Responsable de IVA')], default='COMUN', max_length=20, verbose_name='Régimen fiscal'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='simbolo_moneda',
            field=models.CharField(default='$', help_text='Símbolo que se muestra antes de los valores (ej: $, €, S/)', max_length=5, verbose_name='Símbolo de moneda'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='sitio_web',
            field=models.URLField(blank=True, default='', verbose_name='Sitio web'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='stock_minimo_global',
            field=models.PositiveIntegerField(default=5, help_text='Stock mínimo por defecto al crear un producto. Se puede sobreescribir producto por producto.', verbose_name='Stock mínimo global'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='telefono_secundario',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Teléfono secundario'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='terminos_condiciones',
            field=models.TextField(blank=True, default='', help_text='Texto que aparecerá en la parte inferior de las facturas', verbose_name='Términos y condiciones'),
        ),
        migrations.AlterField(
            model_name='configuraciongeneral',
            name='direccion',
            field=models.TextField(help_text='Dirección física de la empresa', verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='configuraciongeneral',
            name='impuesto_porcentaje',
            field=models.DecimalField(decimal_places=2, default=19.0, help_text='Porcentaje de IVA aplicado por defecto (ej: 19.00 para 19%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de IVA (%)'),
        ),
        migrations.AlterField(
            model_name='configuraciongeneral',
            name='moneda',
            field=models.CharField(choices=[('COP', 'Peso Colombiano (COP)'), ('USD', 'Dólar Americano (USD)'), ('EUR', 'Euro (EUR)'), ('MXN', 'Peso Mexicano (MXN)'), ('PEN', 'Sol Peruano (PEN)'), ('CLP', 'Peso Chileno (CLP)'), ('ARS', 'Peso Argentino (ARS)')], default='COP', max_length=10, verbose_name='Moneda principal'),
        ),
        migrations.AlterField(
            model_name='configuraciongeneral',
            name='nit',
            field=models.CharField(help_text='NIT o documento tributario de la empresa', max_length=50, verbose_name='NIT / Documento de identidad'),
        ),
        migrations.AlterField(
            model_name='configuraciongeneral',
            name='nombre_empresa',
            field=models.CharField(help_text='Nombre comercial que aparecerá en facturas y documentos', max_length=150, verbose_name='Nombre de la empresa'),
        ),
        migrations.AlterField(
            model_name='configuraciongeneral',
            name='telefono',
            field=models.CharField(max_length=30, verbose_name='Teléfono principal'),
        ),
    ]
