# Generated by Django 6.0.1 on 2026-03-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_configuraciongeneral_alertar_stock_bajo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciongeneral',
            name='tasa_cambio',
            field=models.DecimalField(decimal_places=4, default=1.0, help_text='Tasa de conversión respecto a la moneda base (ej: 1 USD = 4000 COP)', max_digits=12, verbose_name='Tasa de cambio'),
        ),
    ]
