# Generated by Django 5.0.14 on 2026-03-19 00:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalles de Compra',
                'db_table': 'detalle_compra',
            },
        ),
        migrations.CreateModel(
            name='PagoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('YAPE', 'Yape'), ('PLIN', 'Plin'), ('CREDITO', 'Crédito')], default='EFECTIVO', max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pago de Compra',
                'verbose_name_plural': 'Pagos de Compras',
                'db_table': 'pago_compra',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compra', models.CharField(editable=False, max_length=20, unique=True)),
                ('motivo_anulacion', models.TextField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcial'), ('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=10)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'compras',
                'ordering': ['-fecha'],
            },
        ),
    ]
