# Generated by Django 5.0.14 on 2026-04-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_cuentaporpagar'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cuentaporpagar',
            new_name='cuentas_por_proveed_99c906_idx',
            old_name='cpp_proveedor_estado_idx',
        ),
        migrations.RenameIndex(
            model_name='cuentaporpagar',
            new_name='cuentas_por_estado_1f20e3_idx',
            old_name='cpp_estado_vencimiento_idx',
        ),
        migrations.AlterField(
            model_name='cuentaporpagar',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha límite de pago acordada con el proveedor (opcional)', null=True),
        ),
        migrations.AlterField(
            model_name='cuentaporpagar',
            name='notas',
            field=models.TextField(blank=True, help_text='Notas adicionales sobre la deuda', null=True),
        ),
    ]
