# Generated by Django 6.0.1 on 2026-02-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_alter_compra_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ANULADA', 'Anulada'), ('REALIZADA', 'Realizada')], default='PENDIENTE', max_length=10),
        ),
    ]
