# Generated by Django 6.0.1 on 2026-02-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_compra_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='motivo_anulacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
