# Generated by Django 6.0.1 on 2026-02-15 16:36

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_compra_motivo_anulacion'),
        ('proveedores', '0002_rename_activo_proveedor_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='numero_compra',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['numero_compra'], name='compras_numero__a90038_idx'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['proveedor'], name='compras_proveed_c6e737_idx'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['estado'], name='compras_estado_9eba4f_idx'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['fecha'], name='compras_fecha_6905b3_idx'),
        ),
    ]
