# Generated by Django 6.0.1 on 2026-02-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_compra_numero_compra_alter_compra_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='numero_compra',
            field=models.CharField(default='TEMP', editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
