# Generated by Django 6.0.1 on 2026-02-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='activo',
            new_name='estado',
        ),
    ]
