# Generated by Django 5.0.14 on 2026-04-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0001_initial'),
        ('productos', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listapreciocompra',
            options={'verbose_name': 'Lista de precio de compra', 'verbose_name_plural': 'Lista de precios de compra'},
        ),
        migrations.AddConstraint(
            model_name='listapreciocompra',
            constraint=models.UniqueConstraint(condition=models.Q(('vigente', True)), fields=('producto', 'proveedor'), name='unique_precio_vigente_por_producto_proveedor'),
        ),
        migrations.AlterModelTable(
            name='listapreciocompra',
            table='lista_precio_compra',
        ),
    ]
