# Generated by Django 5.0.14 on 2026-03-19 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nombre', models.CharField(blank=True, default='', help_text='Nombre del usuario (guardado para historial aunque se elimine el usuario)', max_length=150, verbose_name='Nombre de usuario')),
                ('accion', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('LOGIN_FALLIDO', 'Intento de login fallido'), ('CREAR', 'Crear'), ('LEER', 'Consultar'), ('ACTUALIZAR', 'Actualizar'), ('ELIMINAR', 'Eliminar'), ('COMPLETAR', 'Completar'), ('CANCELAR', 'Cancelar'), ('ANULAR', 'Anular'), ('APROBAR', 'Aprobar'), ('RECHAZAR', 'Rechazar'), ('AJUSTAR_STOCK', 'Ajustar Stock'), ('EXPORTAR', 'Exportar'), ('IMPRIMIR', 'Imprimir/Generar PDF'), ('ACCESO_DENEGADO', 'Acceso denegado'), ('CAMBIO_CLAVE', 'Cambio de contraseña'), ('ERROR', 'Error del sistema')], db_index=True, help_text='Tipo de acción realizada', max_length=30, verbose_name='Acción')),
                ('modulo', models.CharField(choices=[('USUARIOS', 'Usuarios'), ('CLIENTES', 'Clientes'), ('PROVEEDORES', 'Proveedores'), ('INVENTARIO', 'Inventario'), ('VENTAS', 'Ventas'), ('COMPRAS', 'Compras'), ('CAJA', 'Caja'), ('DOCUMENTOS', 'Documentos'), ('CONFIGURACION', 'Configuración'), ('DASHBOARD', 'Dashboard'), ('SISTEMA', 'Sistema')], db_index=True, default='SISTEMA', help_text='Módulo del ERP donde ocurrió la acción', max_length=30, verbose_name='Módulo')),
                ('nivel', models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('CRITICAL', 'Crítico')], db_index=True, default='INFO', help_text='Severidad del log', max_length=10, verbose_name='Nivel')),
                ('descripcion', models.TextField(help_text='Descripción detallada de la acción realizada', verbose_name='Descripción')),
                ('object_id', models.CharField(blank=True, help_text='ID del registro afectado', max_length=50, null=True, verbose_name='ID del objeto')),
                ('objeto_repr', models.CharField(blank=True, default='', help_text='Representación del objeto al momento del log', max_length=255, verbose_name='Descripción del objeto')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP desde donde se realizó la acción', null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, default='', help_text='Navegador/cliente HTTP utilizado', verbose_name='User Agent')),
                ('endpoint', models.CharField(blank=True, default='', help_text='URL de la API que se llamó', max_length=255, verbose_name='Endpoint')),
                ('metodo_http', models.CharField(blank=True, default='', help_text='GET, POST, PUT, PATCH, DELETE', max_length=10, verbose_name='Método HTTP')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Momento exacto en que ocurrió la acción', verbose_name='Fecha y hora')),
                ('datos_antes', models.JSONField(blank=True, help_text='Estado del objeto ANTES de la acción (para ediciones)', null=True, verbose_name='Datos anteriores')),
                ('datos_despues', models.JSONField(blank=True, help_text='Estado del objeto DESPUÉS de la acción', null=True, verbose_name='Datos nuevos')),
                ('extra', models.JSONField(blank=True, help_text='Cualquier información adicional en formato JSON', null=True, verbose_name='Datos extra')),
                ('exitoso', models.BooleanField(db_index=True, default=True, help_text='Indica si la acción fue exitosa o falló', verbose_name='Exitoso')),
                ('duracion_ms', models.PositiveIntegerField(blank=True, help_text='Tiempo de respuesta en milisegundos', null=True, verbose_name='Duración (ms)')),
                ('content_type', models.ForeignKey(blank=True, help_text='Modelo afectado (Venta, Compra, Producto, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Tipo de objeto')),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
