# Generated by Django 5.0.14 on 2026-03-19 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditorias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='logauditoria',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la acción. NULL si fue el sistema.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['usuario', 'fecha_hora'], name='auditorias__usuario_7b1f70_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['modulo', 'accion'], name='auditorias__modulo_72d530_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['modulo', 'fecha_hora'], name='auditorias__modulo_753230_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['nivel', 'fecha_hora'], name='auditorias__nivel_bb110a_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['content_type', 'object_id'], name='auditorias__content_d95dae_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['ip_address'], name='auditorias__ip_addr_f4182c_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['exitoso', 'fecha_hora'], name='auditorias__exitoso_c3f36f_idx'),
        ),
    ]
