# Generated by Django 5.0.14 on 2026-04-12 22:57

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_cuentaporpagar'),
        ('documentos', '0001_initial'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='documento',
            new_name='documentos__tipo_8a085f_idx',
            old_name='documentos_d_tipo_fe_idx',
        ),
        migrations.AddField(
            model_name='documento',
            name='codigo_verificacion',
            field=models.CharField(blank=True, db_index=True, help_text='Código corto alfanumérico de verificación pública.', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, help_text='Fecha de vencimiento (para ventas a crédito).', null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='hash_verificacion',
            field=models.CharField(blank=True, help_text='SHA-256 del contenido completo para verificación de integridad.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='notas',
            field=models.TextField(blank=True, help_text='Observaciones o motivo de anulación.', null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='numero_secuencia',
            field=models.PositiveIntegerField(blank=True, help_text='Valor numérico exacto de la secuencia (para auditoría de huecos).', null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador público único (no expone PK).', null=True),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['tipo', 'numero_interno'], name='idx_tipo_numero'),
        ),
    ]
