# Generated by Django 6.0.1 on 2026-02-26 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_metodo_pago_venta_monto_recibido_venta_vuelto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='monto_recibido',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='vuelto',
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcial'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='PagoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('YAPE', 'Yape'), ('PLIN', 'Plin'), ('CREDITO', 'Crédito')], default='EFECTIVO', max_length=20)),
                ('monto_recibido', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('vuelto', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Pago de Venta',
                'verbose_name_plural': 'Pagos de Ventas',
                'db_table': 'pago_venta',
                'ordering': ['fecha'],
            },
        ),
    ]
