# Generated by Django 6.0.1 on 2026-03-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_remove_venta_metodo_pago_remove_venta_monto_recibido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='impuesto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
