# Generated by Django on 2026-03-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_venta_impuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_documento',
            field=models.CharField(choices=[('FACTURA', 'Factura'), ('RECIBO', 'Recibo POS')], default='FACTURA', max_length=20),
        ),
    ]
